apiVersion: v1
kind: Secret
metadata:
  name: {{ include "collabmd.fullname" . }}
  labels:
    {{- include "collabmd.labels" . | nindent 4 }}
type: Opaque
stringData:
  AUTH_PASSWORD: {{ .Values.auth.password.value | quote }}
  AUTH_SESSION_SECRET: {{ .Values.auth.sessionSecret.value | quote }}
  AUTH_OIDC_CLIENT_ID: {{ .Values.auth.oidc.clientId | quote }}
  AUTH_OIDC_CLIENT_SECRET: {{ .Values.auth.oidc.clientSecret | quote }}
  COLLABMD_GIT_SSH_PRIVATE_KEY_B64: {{ .Values.git.ssh.privateKeyBase64 | quote }}
